import { SEGMENT_FIELDS_TYPE, SEGMENT_SUBFIELDS_TYPE } from "./segments.types"

export const SEGMENT_FIELDS: SEGMENT_FIELDS_TYPE = {
    MSH: [
        'segment',
        'Encoding Characters',
        'Sending Application',
        'Sending Facility',
        'Receiving Application',
        'Receiving Facility',
        'Date/Time of Message',
        'Security',
        'Message Type',
        'Message Control ID',
        'Processing ID',
        'Version ID',
        'Sequence Number',
        'Continuation Pointer',
        'Accept Acknowledgment Type',
        'Application Acknowledgment Type',
        'Country Code',
        'Character Set',
        'Principal Language Of Message',
        'Alternate Character Set Handling Scheme',
        'Message Profile Identifier'
    ],
    PID: [
        'segment',
        'Set ID - PID',
        'Patient ID',
        'Patient Identifier List',
        'Alternate Patient ID',
        'Patient Name',
        'Mother\'s Maiden Name',
        'Date/Time of Birth',
        'Administrative Sex',
        'Patient Alias',
        'Race',
        'Patient Address',
        'County Code',
        'Phone Number - Home',
        'Phone Number - Business',
        'Primary Language',
        'Marital Status',
        'Religion',
        'Patient Account Number',
        'SSN Number - Patient',
        'Driver\'s License Number - Patient'
    ],
    PV1: [
        'segment',
        'Set ID - PV1',
        'Patient Class',
        'Assigned Patient Location',
        'Admission Type',
        'Preadmit Number',
        'Prior Patient Location',
        'Attending Doctor',
        'Referring Doctor',
        'Consulting Doctor',
        'Hospital Service',
        'Temporary Location',
        'Preadmit Test Indicator',
        'Re-admission Indicator',
        'Admit Source',
        'Ambulatory Status',
        'VIP Indicator',
        'Admitting Doctor',
        'Patient Type',
        'Visit Number',
        'Financial Class',
        'Charge Price Indicator',
        'Courtesy Code',
        'Credit Rating',
        'Contract Code',
        'Contract Effective Date',
        'Contract Amount',
        'Contract Period',
        'Interest Code',
        'Transfer to Bad Debt Code',
        'Transfer to Bad Debt Date',
        'Bad Debt Agency Code',
        'Bad Debt Transfer Amount',
        'Bad Debt Recovery Amount',
        'Delete Account Indicator',
        'Delete Account Date',
        'Discharge Disposition',
        'Discharged to Location',
        'Diet Type',
        'Servicing Facility',
        'Bed Status',
        'Account Status',
        'Pending Location',
        'Prior Temporary Location',
        'Admit Date/Time',
        'Discharge Date/Time',
        'Current Patient Balance',
        'Total Charges',
        'Total Adjustments',
        'Total Payments',
        'Alternate Visit ID',
        'Visit Indicator',
        'Other Healthcare Provider',
        'Service Episode Description',
        'Service Episode Identifier'
    ],
    ORC: [
        'segment',
        'Order Control',
        'Placer Order Number',
        'Filler Order Number',
        'Placer Group Number',
        'Order Status',
        'Response Flag',
        'Quantity/Timing',
        'Parent',
        'Date/Time of Transaction',
        'Entered By',
        'Verified By',
        'Ordering Provider',
        'Enterer\'s Location',
        'Call Back Phone Number',
        'Order Effective Date/Time',
        'Order Control Code Reason',
        'Entering Organization',
        'Entering Device',
        'Action By'
    ],
    OBR: [
        'segment',
        'Set ID - OBR',
        'Placer Order Number',
        'Filler Order Number',
        'Universal Service Identifier',
        'Priority',
        'Requested Date/Time',
        'Observation Date/Time',
        'Observation End Date/Time',
        'Collection Volume',
        'Collector Identifier',
        'Specimen Action Code',
        'Danger Code',
        'Relevant Clinical Info.',
        'Specimen Received Date/Time',
        'Specimen Source',
        'Ordering Provider',
        'Order Callback Phone Number',
        'Placer Field 1',
        'Placer Field 2',
        'Filler Field 1',
        'Filler Field 2',
        'Results Rpt/Status Chng - Date/Time',
        'Charge to Practice',
        'Diagnostic Serv Sect ID',
        'Result Status',
        'Parent Result',
        'Quantity/Timing',
        'Result Copies To',
        'Parent',
        'Transportation Mode',
        'Reason for Study',
        'Principal Result Interpreter',
        'Assistant Result Interpreter',
        'Technician',
        'Transcriptionist',
        'Scheduled Date/Time',
        'Number of Sample Containers',
        'Transport Logistics of Collected Sample',
        'Collector\'s Comment',
        'Transport Arrangement Responsibility',
        'Transport Arranged',
        'Escort Required',
        'Planned Patient Transport Comment',
        'Procedure Code',
        'Procedure Code Modifier',
        'Placer Supplemental Service Info.',
        'Filler Supplemental Service Info.',
    ],
    OBX: [
        'segment',
        'Set ID - OBX',
        'Value Type',
        'Observation Identifier',
        'Observation Sub-ID',
        'Observation Value',
        'Units',
        'References Range',
        'Abnormal Flags',
        'Probability',
        'Nature of Abnormal Test',
    ]
}

export const SEGMENT_SUBFIELDS: SEGMENT_SUBFIELDS_TYPE = {
    MSH: {    
        'Sending Facility': [
            'Namespace ID',
            'Universal ID',
            'Universal ID Type',
        ],
        'Message Type': [
            'Message Code',
            'Trigger Event',
        ]
    },
    PID: {
        'Patient Identifier List': [
            'Number',
            'Assigning Authority',
        ],
        'Patient Name': [
            'Family Name',
            'Given Name',
            'Prefix',
        ],
        'Patient Address': [
            'Street Address',
            'City',
            'State',
            'Zip',
            'Country'
        ],
        'Phone Number - Home': [
            'Local Number'
        ]
    },
    PV1: {
        'Referring Doctor': [
            'Number',
            'Family Name',
            'Given Name',
            'Prefix',
        ],
        'Consulting Doctor': [
            'Number',
            'Family Name',
            'Given Name',
            'Prefix',
        ]
    },
    ORC: {
        'Filler Order Number': [
            'Entity Identifier',
            'Namespace ID',
            'Universal ID',
            'Universal ID Type',
        ],
        'Ordering Provider': [
            'Number',
            'Family Name',
            'Given Name',
            'Prefix',
        ],
    },
    OBR: {
        'Filler Order Number': [
            'Entity Identifier',
            'Namespace ID',
            'Universal ID',
            'Universal ID Type',
        ],
        'Universal Service Identifier': [
            'Identifier',
            'Text',
            'Name of Coding System',
        ],
        'Ordering Provider': [
            'Number',
            'Family Name',
            'Given Name',
            'Prefix',
        ],
        'Quantity/Timing': [
            'Start Date/Time',
            'Priority',
        ]
    },
    OBX: {
        'Observation Identifier': [
            'Identifier',
            'Text',
            'Name of Coding System',
        ],
        'Units': [
            'Identifier',
            'Text',
        ],
        'Observation Value': [
            '',
            '',
        ]
    }
}

export const SEGMENT_CONSTANTS = {
    MSH: {
        SEGMENT: 'segment',
        ENCODING_CHARACTERS: 'Encoding Characters',
        SENDING_APPLICATION: 'Sending Application',
        SENDING_FACILITY: 'Sending Facility',
        RECEIVING_APPLICATION: 'Receiving Application',
        RECEIVING_FACILITY: 'Receiving Facility',
        DATE_TIME_OF_MESSAGE: 'Date/Time of Message',
        SECURITY: 'Security',
        MESSAGE_TYPE: 'Message Type',
        MESSAGE_CONTROL_ID: 'Message Control ID',
        PROCESSING_ID: 'Processing ID',
        VERSION_ID: 'Version ID',
        SEQUENCE_NUMBER: 'Sequence Number',
        CONTINUATION_POINTER: 'Continuation Pointer',
        ACCEPT_ACKNOWLEDGMENT_TYPE: 'Accept Acknowledgment Type',
        APPLICATION_ACKNOWLEDGMENT_TYPE: 'Application Acknowledgment Type',
        COUNTRY_CODE: 'Country Code',
        CHARACTER_SET: 'Character Set',
        PRINCIPAL_LANGUAGE_OF_MESSAGE: 'Principal Language Of Message',
        ALTERNATE_CHARACTER_SET_HANDLING_SCHEME: 'Alternate Character Set Handling Scheme',
        MESSAGE_PROFILE_IDENTIFIER: 'Message Profile Identifier'
    },
    PID: {
        SEGMENT: 'segment',
        SET_ID: 'Set ID - PID',
        PATIENT_ID: 'Patient ID',
        PATIENT_IDENTIFIER_LIST: 'Patient Identifier List',
        ALTERNATE_PATIENT_ID: 'Alternate Patient ID',
        PATIENT_NAME: 'Patient Name',
        MOTHERS_MAIDEN_NAME: 'Mother\'s Maiden Name',
        DATE_TIME_OF_BIRTH: 'Date/Time of Birth',
        ADMINISTRATIVE_SEX: 'Administrative Sex',
        PATIENT_ALIAS: 'Patient Alias',
        RACE: 'Race',
        PATIENT_ADDRESS: 'Patient Address',
        COUNTY_CODE: 'County Code',
        PHONE_NUMBER_HOME: 'Phone Number - Home',
        PHONE_NUMBER_BUSINESS: 'Phone Number - Business',
        PRIMARY_LANGUAGE: 'Primary Language',
        MARITAL_STATUS: 'Marital Status',
        RELIGION: 'Religion',
        PATIENT_ACCOUNT_NUMBER: 'Patient Account Number',
        SSN_NUMBER_PATIENT: 'SSN Number - Patient',
        DRIVERS_LICENSE_NUMBER_PATIENT: 'Driver\'s License Number - Patient'
    },
    OBX: {
        SEGMENT: 'segment',
        SET_ID: 'Set ID - OBX',
        VALUE_TYPE: 'Value Type',
        OBSERVATION_IDENTIFIER: 'Observation Identifier',
        OBSERVATION_SUB_ID: 'Observation Sub-ID',
        OBSERVATION_VALUE: 'Observation Value',
        UNITS: 'Units',
        REFERENCES_RANGE: 'References Range',
        ABNORMAL_FLAGS: 'Abnormal Flags',
        PROBABILITY: 'Probability',
        NATURE_OF_ABNORMAL_TEST: 'Nature of Abnormal Test',
    }
}